import { Term } from './types';

export const TERMS_DATA: Term[] = [
  // Legal & Regulatory
  { id: 'l1', category: 'Legal & Regulatory', term: 'Telephone Consumer Protection Act (TCPA)' },
  { id: 'l2', category: 'Legal & Regulatory', term: 'Florida Telephone Solicitation Act (FTSA)' },
  { id: 'l3', category: 'Legal & Regulatory', term: 'Oklahoma Telephone Solicitation Act (OTSA)' },
  { id: 'l4', category: 'Legal & Regulatory', term: 'Telemarketing Sales Rule (TSR)' },
  { id: 'l5', category: 'Legal & Regulatory', term: 'Federal Communications Commission (FCC)' },
  { id: 'l6', category: 'Legal & Regulatory', term: 'Federal Trade Commission (FTC)' },
  { id: 'l7', category: 'Legal & Regulatory', term: 'Prior Express Written Consent (PEWC)' },
  { id: 'l8', category: 'Legal & Regulatory', term: 'Prior Express Consent (PEC)' },
  { id: 'l9', category: 'Legal & Regulatory', term: 'Prior Express Invitation or Permission (PEIP)' },
  { id: 'l10', category: 'Legal & Regulatory', term: 'One-to-One Consent (1:1 Consent)' },
  { id: 'l11', category: 'Legal & Regulatory', term: 'Lead Generator Loophole' },
  { id: 'l12', category: 'Legal & Regulatory', term: 'Revocation of Consent' },
  { id: 'l13', category: 'Legal & Regulatory', term: 'Revoke All Rule' },
  { id: 'l14', category: 'Legal & Regulatory', term: 'Reasonable Means (of Revocation)' },
  { id: 'l15', category: 'Legal & Regulatory', term: 'Safe Harbor (TCPA/DNC)' },
  { id: 'l16', category: 'Legal & Regulatory', term: 'National Do Not Call (DNC) Registry' },
  { id: 'l17', category: 'Legal & Regulatory', term: 'Internal DNC List' },
  { id: 'l18', category: 'Legal & Regulatory', term: 'Reassigned Numbers Database (RND)' },
  { id: 'l19', category: 'Legal & Regulatory', term: 'Automatic Telephone Dialing System (ATDS)' },
  { id: 'l20', category: 'Legal & Regulatory', term: 'Artificial or Prerecorded Voice' },
  { id: 'l21', category: 'Legal & Regulatory', term: 'AI-Generated Voice / Robocalls' },
  { id: 'l22', category: 'Legal & Regulatory', term: 'Clear and Conspicuous Disclosure' },
  { id: 'l23', category: 'Legal & Regulatory', term: 'Logically and Topically Associated' },
  { id: 'l24', category: 'Legal & Regulatory', term: 'Private Right of Action' },
  { id: 'l25', category: 'Legal & Regulatory', term: 'Statutory Damages / Treble Damages' },
  { id: 'l26', category: 'Legal & Regulatory', term: 'Professional Litigators / Serial Plaintiffs' },
  { id: 'l27', category: 'Legal & Regulatory', term: 'E-SIGN Act' },
  { id: 'l28', category: 'Legal & Regulatory', term: 'STIR/SHAKEN' },
  { id: 'l29', category: 'Legal & Regulatory', term: '10-Day Processing Window (for Revocation)' },
  { id: 'l30', category: 'Legal & Regulatory', term: 'Clarification Message' },

  // Advertising & Lead Generation
  { id: 'a1', category: 'Advertising Ecosystem', term: 'Programmatic Advertising' },
  { id: 'a2', category: 'Advertising Ecosystem', term: 'Real-Time Bidding (RTB)' },
  { id: 'a3', category: 'Advertising Ecosystem', term: 'Demand Side Platform (DSP)' },
  { id: 'a4', category: 'Advertising Ecosystem', term: 'Supply Side Platform (SSP)' },
  { id: 'a5', category: 'Advertising Ecosystem', term: 'Ad Exchange' },
  { id: 'a6', category: 'Advertising Ecosystem', term: 'Publishers' },
  { id: 'a7', category: 'Advertising Ecosystem', term: 'Lead Aggregators / Lead Vendors' },
  { id: 'a8', category: 'Advertising Ecosystem', term: 'Exclusive Leads' },
  { id: 'a9', category: 'Advertising Ecosystem', term: 'Shared Leads' },
  { id: 'a10', category: 'Advertising Ecosystem', term: 'Data Leads' },
  { id: 'a11', category: 'Advertising Ecosystem', term: 'Live Transfers / Warm Transfers' },
  { id: 'a12', category: 'Advertising Ecosystem', term: 'Inbound Calls' },
  { id: 'a13', category: 'Advertising Ecosystem', term: 'Click-to-Call' },
  { id: 'a14', category: 'Advertising Ecosystem', term: 'Aged Leads' },
  { id: 'a15', category: 'Advertising Ecosystem', term: 'Incentivized Leads / Bait-and-Switch' },
  { id: 'a16', category: 'Advertising Ecosystem', term: 'Ping Post / Ping Tree' },
  { id: 'a17', category: 'Advertising Ecosystem', term: 'Lead Capture Form / Quote Funnel' },
  { id: 'a18', category: 'Advertising Ecosystem', term: 'Organic vs. Inorganic Marketing' },
  { id: 'a19', category: 'Advertising Ecosystem', term: 'Lead Magnet' },
  { id: 'a20', category: 'Advertising Ecosystem', term: 'Session Replay' },
  { id: 'a21', category: 'Advertising Ecosystem', term: 'TrustedForm (ActiveProspect)' },
  { id: 'a22', category: 'Advertising Ecosystem', term: 'Jornaya (Verisk)' },
  { id: 'a23', category: 'Advertising Ecosystem', term: 'Token / Certificate of Authenticity' },

  // Metrics
  { id: 'm1', category: 'Metrics & KPIs', term: 'Cost Per Acquisition (CPA)' },
  { id: 'm2', category: 'Metrics & KPIs', term: 'Cost Per Lead (CPL)' },
  { id: 'm3', category: 'Metrics & KPIs', term: 'Cost Per Click (CPC)' },
  { id: 'm4', category: 'Metrics & KPIs', term: 'Cost Per Sale (CPS)' },
  { id: 'm5', category: 'Metrics & KPIs', term: 'Cost Per Quote' },
  { id: 'm6', category: 'Metrics & KPIs', term: 'Click-Through Rate (CTR)' },
  { id: 'm7', category: 'Metrics & KPIs', term: 'Conversion Rate (CVR)' },
  { id: 'm8', category: 'Metrics & KPIs', term: 'Click-to-Lead Conversion' },
  { id: 'm9', category: 'Metrics & KPIs', term: 'Lead-to-Quote Rate' },
  { id: 'm10', category: 'Metrics & KPIs', term: 'Quote-to-Close / Quote-to-Bind Rate' },
  { id: 'm11', category: 'Metrics & KPIs', term: 'Contact Rate' },
  { id: 'm12', category: 'Metrics & KPIs', term: 'Return on Ad Spend (ROAS)' },
  { id: 'm13', category: 'Metrics & KPIs', term: 'Return on Investment (ROI)' },
  { id: 'm14', category: 'Metrics & KPIs', term: 'Lifetime Value (LTV)' },
  { id: 'm15', category: 'Metrics & KPIs', term: 'LTV / CAC Ratio' },
  { id: 'm16', category: 'Metrics & KPIs', term: 'Premium Per Household' },
  { id: 'm17', category: 'Metrics & KPIs', term: 'Items Per Household' },
  { id: 'm18', category: 'Metrics & KPIs', term: 'Vanity Metrics vs. Sanity Metrics' },
  { id: 'm19', category: 'Metrics & KPIs', term: 'Data Maturity' },

  // Insurance Concepts
  { id: 'i1', category: 'Insurance Concepts', term: 'Captive Agents' },
  { id: 'i2', category: 'Insurance Concepts', term: 'Independent Agents (Brokers)' },
  { id: 'i3', category: 'Insurance Concepts', term: 'Property and Casualty (P&C)' },
  { id: 'i4', category: 'Insurance Concepts', term: 'Monoline Policy' },
  { id: 'i5', category: 'Insurance Concepts', term: 'Multi-line / Bundling' },
  { id: 'i6', category: 'Insurance Concepts', term: 'Variable Compensation (VC)' },
  { id: 'i7', category: 'Insurance Concepts', term: 'Loss Ratio' },
  { id: 'i8', category: 'Insurance Concepts', term: 'Retention Rate / Lapse Rate' },
  { id: 'i9', category: 'Insurance Concepts', term: 'Underwriting Guidelines' },
  { id: 'i10', category: 'Insurance Concepts', term: 'Risk Profile' },
  { id: 'i11', category: 'Insurance Concepts', term: 'Preferred Customer' },
  { id: 'i12', category: 'Insurance Concepts', term: 'Non-Standard Customer' },
  { id: 'i13', category: 'Insurance Concepts', term: 'SR-22' },
  { id: 'i14', category: 'Insurance Concepts', term: 'Continuous Coverage' },
  { id: 'i15', category: 'Insurance Concepts', term: 'Prior Coverage' },
  { id: 'i16', category: 'Insurance Concepts', term: 'Approved Vendor List' },
  { id: 'i17', category: 'Insurance Concepts', term: 'Carrier Appointments' },

  // GOAL Strategy
  { id: 'g1', category: 'GOAL Strategy', term: 'Bid Modifiers' },
  { id: 'g2', category: 'GOAL Strategy', term: 'Base Bid' },
  { id: 'g3', category: 'GOAL Strategy', term: 'Targeting Criteria (Filters)' },
  { id: 'g4', category: 'GOAL Strategy', term: 'Ad Groups' },
  { id: 'g5', category: 'GOAL Strategy', term: 'Day-Parting / Scheduling' },
  { id: 'g6', category: 'GOAL Strategy', term: 'Geotargeting' },
  { id: 'g7', category: 'GOAL Strategy', term: 'Source Transparency / Source Channel' },
  { id: 'g8', category: 'GOAL Strategy', term: 'Publisher ID' },
  { id: 'g9', category: 'GOAL Strategy', term: 'Right Pricing' },
  { id: 'g10', category: 'GOAL Strategy', term: 'Campaign Optimization' },
  { id: 'g11', category: 'GOAL Strategy', term: 'Ad Creatives (Static vs. Animated)' },
  { id: 'g12', category: 'GOAL Strategy', term: 'A/B Testing' },
  { id: 'g13', category: 'GOAL Strategy', term: 'Account Review' },
  { id: 'g14', category: 'GOAL Strategy', term: 'Feedback Loop / Disposition Data' },
  { id: 'g15', category: 'GOAL Strategy', term: 'Smart Money' },
  { id: 'g16', category: 'GOAL Strategy', term: 'Consultative Sales Approach' },

  // Technology
  { id: 't1', category: 'Technology', term: 'Customer Relationship Management (CRM)' },
  { id: 't2', category: 'Technology', term: 'Lead Management System (LMS)' },
  { id: 't3', category: 'Technology', term: 'Salesforce' },
  { id: 't4', category: 'Technology', term: 'Close.io' },
  { id: 't5', category: 'Technology', term: 'Lead Manager (Allstate)' },
  { id: 't6', category: 'Technology', term: 'Ricochet360' },
  { id: 't7', category: 'Technology', term: 'QuoteBurst' },
  { id: 't8', category: 'Technology', term: 'AgencyZoom' },
  { id: 't9', category: 'Technology', term: 'EZLynx' },
  { id: 't10', category: 'Technology', term: 'Velocify' },
  { id: 't11', category: 'Technology', term: 'Fathom (AI Notetaker)' },
  { id: 't12', category: 'Technology', term: 'Periscope (Data Visualization)' },
  { id: 't13', category: 'Technology', term: 'NotebookLM' },

  // Competitors
  { id: 'c1', category: 'Competitors', term: 'EverQuote' },
  { id: 'c2', category: 'Competitors', term: 'QuoteWizard (LendingTree)' },
  { id: 'c3', category: 'Competitors', term: 'SmartFinancial' },
  { id: 'c4', category: 'Competitors', term: 'MediaAlpha' },
  { id: 'c5', category: 'Competitors', term: 'NextGen Leads' },
  { id: 'c6', category: 'Competitors', term: 'Hometown Quotes' },
  { id: 'c7', category: 'Competitors', term: 'Datalot (Centerfield)' },
  { id: 'c8', category: 'Competitors', term: 'Internet Leads (General Term)' },
];